# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# etc/samples/single_user/light.yaml
apiVersion: sandmold.io/v1alpha1
kind: UserSetup
metadata:
  name: ricc-light-setup
spec:
  user_email: riccardo@example.com
  # To create a new project, use project_id. A random suffix will be added.
  project_id: riccardo-light
  # To use an existing project, uncomment the following line and provide the exact project ID.
  # existing_project_id: your-existing-project-id
  billing_account_id: "XXXXXX-XXXXXX-XXXXXX"