
apiVersion: sandmold.dev/v1alpha1
kind: Blueprint
metadata:
  name: bank-of-anthos
spec:
  description: "A sample blueprint for the Bank of Anthos microservices demo, inspired by K8s/KCC objects."
  emoji: "🏦"
  # dependsOn:
  # - sandmold.dev/v1alpha1/Folder
  # - sandmold.dev/v1alpha1/Project
  install: TODO
  repo: https://github.com/GoogleCloudPlatform/bank-of-anthos
  variables:
    - name: PROJECT_ID
      description: "The Google Cloud Project ID to deploy Bank of Anthos to."
    - name: REGION
      description: "The Google Cloud region to deploy Bank of Anthos to."
  gcp_prerequisites:
    APIs:
      - name: container.googleapis.com
        description: "Google Kubernetes Engine API"
      - name: cloudresourcemanager.googleapis.com
        description: "Cloud Resource Manager API"
      - name: iam.googleapis.com
        description: "Identity and Access Management API"
      # - name: cloudbilling.googleapis.com
      #   description: "Cloud Billing API"
