# yaml dammit YAML support!!!!!
apiVersion: sandmold.io/v1alpha1
kind: Classroom
metadata:
  name: class-2teachers-6students
  labels:
    class: class_2teachers_6
    author: ricc
spec:
  folder:
    org_id: 791852209422
    parent_folder_id: '1000371719973'
    billing_account_id: "01C588-4823BC-27F650"
    displayName: 2 teachers 6 students
    domain: sredemo.dev
    description: Class with 2 teachers and 6 students
    teachers:
    - leoy@google.com
    - ricc@google.com
    env:
      - name: TF_VAR_GOOGLE_CLOUD_REGION
        value: us-central1
  schoolbenches:
    # schoolbench 1
    - project: teacherz  # will be padded by some random hex/numb
      desk-type: teacher
      apps:
      - online-boutique
      - bank-of-anthos
      - sandmold-web
      seats:
      - leoy@google.com
      - ricc@google.com
    # schoolbench 2
    - project: project-boa01  # will be padded by some random hex/numb, -> "boa01-123abc"
      apps:
      - online-boutique
      seats:
      - student01@gmail.com
      - student02@gmail.com
    - apps:
      - online-boutique
      project: project-boa02
      seats:
      - student03@gmail.com
      - student04@gmail.com
    - app: online-boutique
      project: project-boa03
      seats:
      - student06@gmail.com
      - palladiusbonton@gmail.com
