# etc/project_config.yaml

# This file defines the standard configuration for a project created by sandmold.
# It is consumed by the preparation scripts and passed into the Terraform modules.
# You can modify this file to customize the project setup.

# A list of Google Cloud APIs that should be enabled on the project.
services_to_enable:
  - aiplatform.googleapis.com
  - artifactregistry.googleapis.com
  - cloudbuild.googleapis.com
  - cloudresourcemanager.googleapis.com
  - compute.googleapis.com
  - run.googleapis.com
  - serviceusage.googleapis.com
  - iam.googleapis.com
  - monitoring.googleapis.com
  - logging.googleapis.com
  - apphub.googleapis.com

# A map of IAM roles to the principals who should be granted them.
# The Python script will transform this into the format needed by the Terraform module.
iam_permissions:
  # Project-level roles for the student/user of the project.
  user_roles:
    - roles/editor
    - roles/iam.serviceAccountUser
    - roles/run.admin
    - roles/artifactregistry.writer
    - roles/storage.admin
    - roles/aiplatform.user

  teacher_roles_in_teacher_project:
    - roles/editor
    - roles/iam.serviceAccountUser
    - roles/run.admin
    - roles/artifactregistry.writer
    - roles/storage.admin
    - roles/aiplatform.user

  teacher_roles_in_students_project:
    - roles/owner
    - roles/iam.serviceAccountUser
    - roles/iam.administrator

  # Additional roles can be defined here if needed.
folders:
  tags:
    # Labels to apply to the folders created for the project.
    environment: development
    #team: data-science
    createdby: sandmold

projects:
  tags:
    # Labels to apply to the projects created by sandmold.
    environment: development
    #team: data-science
    createdby: sandmold
