
TERRAFORM_CLASSROOM_FOLDER_DIR := "terraform-modules/terraform-classroom-folder"

# list targets
list:
    just -l

# create SaaS Runtime instance
create-saas:
    #!/bin/bash
    source .env
    bin/01-create-saas.sh

check:
    #!/bin/bash
    source .env

    echo -e "\n\033[0;36m🗂️ Listing Project config:\033[0m"
    gcloud config list 2>/dev/null | egrep "account =|project ="

    echo -e "\n\033[0;36m🚀 Listing SaaS instances (filtered by 'sandmold'):\033[0m"
    gcloud beta saas-runtime saas list --filter="name~sandmold" --format="table(name,createTime,updateTime)" --location=global

    echo -e "\n\033[0;36m🧩 Listing Unit Kinds (filtered by 'sandmold'):\033[0m"
    gcloud beta saas-runtime unit-kinds list --filter="name~sandmold" --format="table(name,saas,defaultRelease)" --location=global

    echo -e "\n\033[0;36m📦 Listing Units (filtered by 'sandmold'):\033[0m"
    gcloud beta saas-runtime units list --filter="name~sandmold" --format="table(name,unitKind,state)" --location="${GOOGLE_CLOUD_REGION}"



create-classroom-folder-unit-kind:
    #!/bin/bash
    source .env
    bin/03-create-unit-kind.sh classroom-folder {{TERRAFORM_CLASSROOM_FOLDER_DIR}}

create-sample-vm-unit-kind:
    #!/bin/bash
    source .env
    bin/03-create-unit-kind.sh sandmold-sample-vm terraform-modules/terraform-vm

build-and-push-blueprint:
    #!/bin/bash
    source .env
    bin/05-build-and-push-blueprint.sh {{TERRAFORM_CLASSROOM_FOLDER_DIR}}

docker check:
    docker ps
