
TERRAFORM_CLASSROOM_FOLDER_DIR := "terraform-modules/terraform-classroom-folder"

# list targets
list:
    just -l

# create SaaS Runtime instance
create-saas:
    #!/bin/bash
    source .env
    bin/01-create-saas.sh

check:
    #!/bin/bash
    bin/check-saas-status.sh



create-classroom-folder-unit-kind:
    #!/bin/bash
    source .env
    bin/03-create-unit-kind.sh classroom-folder {{TERRAFORM_CLASSROOM_FOLDER_DIR}}

create-sample-vm-unit-kind:
    #!/bin/bash
    source .env
    bin/03-create-unit-kind.sh sandmold-sample-vm terraform-modules/terraform-vm

build-and-push-blueprint:
    #!/bin/bash
    source .env
    bin/05-build-and-push-blueprint.sh {{TERRAFORM_CLASSROOM_FOLDER_DIR}}

docker check:
    docker ps
