
# Lists foobar app verbs
list:
    echo "Application in foobar:"
    just -l

start:
    ./start.sh
stop:
    ./stop.sh
status:
    ./status.sh

test-verb VERB:
    GOOGLE_CLOUD_PROJECT="ricc-genai" \
    GOOGLE_CLOUD_REGION="your-gcp-region" \
    SLEEP_TIME="1" \
    AUTO_FAIL="No, thanks I'm just a justfile" \
    just {{VERB}}
