# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# My second class.
apiVersion: sandmold.io/v1alpha1
kind: Classroom
metadata:
  # Do NOT change this!
  name: ng2teachers-4realstudents
  labels:
    classroom: 2teachers_4realstudents
    author: ricc
    env: development

spec:
  folder:
    #org_id: 123456789012 # example.com
    #parent_folder_id: "987654321098" # example.com / test-sandmold / sandmold-1
    #billing_account_id: "XXXXXX-XXXXXX-XXXXXX"  OBSOLETE, now taking it from ENV.
    #OBSOLETE displayName: Two teachers 4 real students NG
    #domain: example.com
    description: |
      Class with 3 teachers and 4 real students
    teachers:
    - riccardo@example.com
    - leonie@example.com
    - teacher3@example.com
    env:
      - name: GOOGLE_CLOUD_REGION
        value: europe-west4

  schoolbenches:
    - project: teacherz-ng
      desk-type: teacher
      seats:
      - riccardo@example.com
      - generic.user@example.com

    # schoolbench 2
    - project: project-leo-ng
      seats:
      - leonie@example.com

    - project: daniel-ng
      seats:
      - teacher3@example.com

    - project: babenko-ng
      seats:
      - student4@example.com

    - project: ricc-personal-ng
      seats:
      - generic.user@example.com

  common:
    schoolbenches:
      # common to all schoolbenches  - TODO(gemini-cli): to be implemented
      foreach_project:
        applies_to: ALL_STUDENTS  # Can be _ALL or  _ALL_STUDENTS and it becomes an iteration over the following list.
        # adds this apps to all student apps.
        apps:
        - online-boutique
        - foobar
        # adds this person to all students
        seats:
        - riccardo@example.com
