# My second class.
apiVersion: sandmold.io/v1alpha1
kind: Classroom
metadata:
  # Do NOT change this!
  name: ng2teachers-4realstudents
  labels:
    classroom: 2teachers_4realstudents
    author: ricc
    env: development

spec:
  folder:
    org_id: 791852209422 # sredemo.dev
    parent_folder_id: "194703823593" # sredemo.dev / test-sandmold / sandmold-1
    #billing_account_id: "01C588-4823BC-27F650"  OBSOLETE, now taking it from ENV.
    #OBSOLETE displayName: Two teachers 4 real students NG
    domain: sredemo.dev
    description: |
      Class with 3 teachers and 4 real students
    teachers:
    - ricc@google.com
    - leoy@google.com
    - stamer@google.com
    env:
      - name: GOOGLE_CLOUD_REGION
        value: europe-west4

  schoolbenches:
    - project: teacherz-ng
      desk-type: teacher
      seats:
      - ricc@google.com
      - palladiusbonton@gmail.com

    # schoolbench 2
    - project: project-leo-ng
      seats:
      - leoy@google.com

    - project: daniel-ng
      seats:
      - stamer@google.com

    - project: babenko-ng
      seats:
      - babenko@google.com

    - project: ricc-personal-ng
      seats:
      - palladiusbonton@gmail.com

  common:
    schoolbenches:
      # common to all schoolbenches  - TODO(gemini-cli): to be implemented
      foreach_project:
        applies_to: ALL_STUDENTS  # Can be _ALL or  _ALL_STUDENTS and it becomes an iteration over the following list.
        # adds this apps to all student apps.
        apps:
        - online-boutique
        - foobar
        # adds this person to all students
        seats:
        - ricc@google.com
