# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is the SAMPLE YAML from justfile
apiVersion: sandmold.io/v1alpha1
kind: Classroom
metadata:
  name: ng2teachers-3x2students
  labels:
    classroom: 2teachers_3x2students
    author: ricc
    env: development
spec:
  folder:
    #OBSOLETE displayName: ng2teachers-3x2students
    #domain: example.com
    description: |
      Class with 2 teachers and 6 students,
      2 students per bench (in team).
      This is also the SAMPLE classroom YAML
      used by the justfile targets.
    teachers:
    - riccardo@example.com
    - leonie@example.com
    env:
      - name: GOOGLE_CLOUD_REGION
        value: europe-west1
    prefix: fb1 # TODO not implemented yet
  schoolbenches:
    - project: teacherz  # will be padded by some random hex/numb
      desk-type: teacher
      apps:
      - bank-of-anthos
      - sandmold-web
      seats:
      - riccardo@example.com
      - leonie@example.com
    - project: foobar01  # will be padded by some random hex/numb, -> "boa01-123abc"
      seats:
      - student01@gmail.com
      - student02@gmail.com
    - project: foobar02
      seats:
      - student03@gmail.com
      - student04@gmail.com
    - project: foobar03
      seats:
      - student05@gmail.com
      - generic.user@example.com
    - project: failing-foobar
      seats:
      - admin@example.com
      env:
      - name: AUTO_FAIL
        value: omega13
  common:
    schoolbenches:
      foreach_project:
        applies_to: ALL_STUDENTS
        apps:
        - online-boutique
